name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title.trim();
            const versionBumpMarker = /^(?:\((feat|fix|docs)\)|BREAKING:)\s/;
            const ticketExists = /^(?:\((feat|fix|docs)\)|BREAKING:)\s+(\w+\s?-\s?\w+)/;
            const validTicketFormat = /^(?:\((feat|fix|docs)\)|BREAKING:)\s+[A-Z][a-zA-Z0-9]*-\d{1,8}:/;
            const descriptionAfterMarker = /^(?:\((feat|fix|docs)\)|BREAKING:)\s+\w(?:.+)?/;
            const descriptionAfterTicket = /^(?:\((feat|fix|docs)\)|BREAKING:)\s+(\w+\s?-\s?\w+):\s+?\w(.+)?/;
            
            if (!versionBumpMarker.test(title)) {
              core.setFailed(`
                ❌ Invalid PR title prefix. Must start with one of these:
                • "(feat) "
                • "(fix) "
                • "(docs) "
                • "BREAKING: "

                Examples:
                - "(feat) Add new login button"
                - "(fix) O3-1234: Resize header"
                - "BREAKING: Remove deprecated API"

                Your title: "${title}"
              `);
              return;
            }
            
            
            if (ticketExists.test(title)) {
              if (!validTicketFormat.test(title)) {
                core.setFailed(
                  'Invalid ticket format boy'
                )
                return;
              }
            } else {
              const descriptionAfterMarker = /^(?:\((feat|fix|docs)\)|BREAKING:)\s+\w(?:.+)?/;
              if (!descriptionAfterMarker.test(title)) {
                core.setFailed(`
                  ❌ Invalid PR title format. Must include a description.
                  Example: "(feat) O3-1234: Add new login button"
                  Your title: "${title}"
                `);
                return;
              } else {
                core.info(`✅ Valid PR title prefix: "${title}"`);
                return;
              }
            }
            
            if (!descriptionAfterTicket.test(title)) {
              core.setFailed(`
                ❌ Invalid PR title format. Must include a description.
                Example: "(feat) O3-1234: Add new login button"
                Your title: "${title}"
              `);
              return;
            }

            core.info(`✅ Valid PR title: "${title}"`);
